export const PIXEL_DATA = {
  user: {
    handle: 'vodtinker',
    name: 'Daniel Fonov',
    class: 'ASIR / WEB-DEV',
    level: 21,
    xp: 6800,
    xpMax: 10000,
  },

  socials: [
    { id: 'github',   label: 'GitHub',   handle: '@VodTinker',          url: 'https://github.com/VodTinker',          glyph: 'GH' },
    { id: 'mail',     label: 'E-Mail',   handle: 'danielfonov71@gmail.com', url: 'mailto:danielfonov71@gmail.com',    glyph: 'M'  },
    { id: 'linkedin', label: 'LinkedIn', handle: '/in/daniel-fonov',     url: 'https://linkedin.com/in/daniel-fonov', glyph: 'IN' },
    { id: 'discord',  label: 'Discord',  handle: 'vodtinker',            url: '#',                                    glyph: 'DC' },
  ],

  zones: [
    { id: 'about',    x: 14, y: 32 },
    { id: 'projects', x: 50, y: 22 },
    { id: 'stack',    x: 78, y: 38 },
    { id: 'xp',       x: 30, y: 65 },
    { id: 'comms',    x: 66, y: 70 },
  ],

  projects: [
    {
      id: 'mail-infra',
      title: 'Mail & DNS Infra',
      tagline: { en: 'Self-hosted mail & encrypted DNS', es: 'Correo y DNS cifrado propio' },
      desc: {
        en: 'Full mail + DNS stack with Stalwart (Rust), JMAP/IMAP/SMTP, DoH/DoQ, auto-backups, zero downtime.',
        es: 'Stack completo de correo + DNS con Stalwart (Rust), JMAP/IMAP/SMTP, DoH/DoQ, backups automáticos.',
      },
      tags: ['Rust', 'Stalwart', 'DNS', 'Caddy', 'Tailscale'],
      stats: { stars: 0, lvl: 'S', status: 'live' as const },
      color: 'cyan',
      link: 'https://mail.vodtinker.dev',
      details: {
        date: '2023 – present',
        features: {
          en: ['Stalwart JMAP/IMAP/SMTP + DoH/DoQ', 'Nightly encrypted backups to NAS', 'Zero-downtime deploys via Tailscale', 'Caddy reverse proxy + auto TLS'],
          es: ['Stalwart JMAP/IMAP/SMTP + DoH/DoQ', 'Backups cifrados nocturnos a NAS', 'Sin downtime via red Tailscale', 'Reverse proxy Caddy + TLS auto'],
        },
        rewards: ['self-hosted mail', 'encrypted DNS', 'zero-downtime ops'],
      },
    },
    {
      id: 'discord-bot',
      title: 'VODGPT Bot',
      tagline: { en: 'Discord bot powered by OpenAI', es: 'Bot de Discord con OpenAI' },
      desc: {
        en: 'Discord bot integrating the OpenAI API for interactive AI responses, image generation, and persistent user context.',
        es: 'Bot de Discord que integra la API de OpenAI para respuestas IA, generación de imágenes y contexto de usuario persistente.',
      },
      tags: ['Node.js', 'Discord.js', 'OpenAI'],
      stats: { stars: 0, lvl: 'A', status: 'live' as const },
      color: 'magenta',
      link: 'https://discord.com/oauth2/authorize?client_id=780039002198638592',
      details: {
        date: '2023',
        features: {
          en: ['GPT-4 chat with persistent context', 'DALL·E image generation on demand', '15+ slash commands + rate limiting', 'Per-user SQLite state tracking'],
          es: ['Chat GPT-4 con contexto persistente', 'Generación de imágenes con DALL·E', '+15 slash commands + rate limiting', 'Estado de usuario en SQLite'],
        },
        rewards: ['OpenAI API', 'Discord.js v14', 'persistent context'],
      },
    },
    {
      id: 'classroom-bot',
      title: 'ClassAlert',
      tagline: { en: 'Classroom notifications to Discord', es: 'Notificaciones de aula a Discord' },
      desc: {
        en: 'n8n automation that monitors virtual classrooms for updates and fires instant Discord alerts when new content is posted.',
        es: 'Automatización n8n que monitorea aulas virtuales y envía alertas instantáneas a Discord cuando hay contenido nuevo.',
      },
      tags: ['n8n', 'Discord', 'JavaScript'],
      stats: { stars: 0, lvl: 'B', status: 'live' as const },
      color: 'gold',
      link: '#',
      details: {
        date: '2024',
        features: {
          en: ['Polls Moodle every 5 min via cron', 'Instant Discord alert on new content', 'Per-subject notification filters', 'n8n webhook chain + no-code flow'],
          es: ['Polling Moodle cada 5 min via cron', 'Alerta Discord al subir contenido', 'Filtros configurables por asignatura', 'Cadena n8n + flujo no-code'],
        },
        rewards: ['n8n automation', 'webhook chains', 'Moodle scraping'],
      },
    },
    {
      id: 'vpn-netbird',
      title: 'Netbird VPN',
      tagline: { en: 'Self-hosted WireGuard mesh VPN', es: 'VPN mesh WireGuard autoalojada' },
      desc: {
        en: 'WireGuard-based mesh VPN with a self-hosted Netbird control plane. Connects homelab, cloud VMs and remote devices with zero relay hops.',
        es: 'VPN mesh basada en WireGuard con plano de control Netbird propio. Conecta homelab, VMs cloud y dispositivos remotos sin relay.',
      },
      tags: ['Netbird', 'WireGuard', 'Linux', 'Docker'],
      stats: { stars: 0, lvl: 'A', status: 'live' as const },
      color: 'violet',
      link: 'https://netbird.vodtinker.dev',
      details: {
        date: '2024 – present',
        features: {
          en: ['Self-hosted Netbird control plane', 'P2P WireGuard — no relay hops', 'ACL rules per device group', 'Connects 10+ nodes across homelab & cloud'],
          es: ['Control plane Netbird propio', 'WireGuard P2P sin saltos relay', 'Reglas ACL por grupo de dispositivo', 'Conecta +10 nodos entre homelab y cloud'],
        },
        rewards: ['WireGuard internals', 'Netbird self-host', 'network ACLs'],
      },
    },
    {
      id: 'openxixon',
      title: 'OpenXixón',
      tagline: { en: 'Open data API for Gijón', es: 'API de datos abiertos de Gijón' },
      desc: {
        en: 'REST API exposing verified Gijón municipal datasets: air quality, public contracts, traffic fines, demographics. Free tier + Pro plan.',
        es: 'API REST con datasets municipales de Gijón verificados: calidad del aire, contratos públicos, multas, demografía. Tier gratuito + plan Pro.',
      },
      tags: ['REST API', 'Open Data', 'TypeScript', 'Cloudflare'],
      stats: { stars: 0, lvl: 'S', status: 'live' as const },
      color: 'cyan',
      link: 'https://openxixon.vodtinker.dev',
      details: {
        date: '2025 – present',
        features: {
          en: ['Air quality: NO₂, O₃, PM10, PM2.5 hourly', 'Public investments & municipal contracts', 'Bearer token auth + edge deployment', 'Free 100 req/day · Pro 10K req/day'],
          es: ['Calidad del aire: NO₂, O₃, PM10 cada hora', 'Inversiones públicas y contratos municipales', 'Auth bearer token + despliegue en edge', 'Gratis 100 req/día · Pro 10K req/día'],
        },
        rewards: ['REST API design', 'open data pipelines', 'edge deployment'],
      },
    },
    {
      id: 'web-scraper',
      title: 'DataHarvest',
      tagline: { en: 'Automated web scraping scripts', es: 'Scripts de scraping automatizados' },
      desc: {
        en: 'Selenium-based Python scripts for automated data collection from multiple sites. Built-in scheduling and export to JSON/CSV.',
        es: 'Scripts Python con Selenium para recolección automática de datos de múltiples sitios. Exporta a JSON/CSV.',
      },
      tags: ['Python', 'Selenium', 'Automation'],
      stats: { stars: 0, lvl: 'B', status: 'live' as const },
      color: 'green',
      link: '#',
      details: {
        date: '2023 – 2024',
        features: {
          en: ['Multi-site concurrent scraping', 'APScheduler built-in cron', 'Export to JSON / CSV / SQLite', 'Proxy rotation + stealth mode'],
          es: ['Scraping concurrente multi-sitio', 'Cron integrado con APScheduler', 'Exporta a JSON / CSV / SQLite', 'Rotación de proxies + stealth mode'],
        },
        rewards: ['Selenium 4', 'async Python', 'data pipelines'],
      },
    },
  ],

  stack: [
    { cat: 'os',    items: ['Linux', 'Debian', 'Arch', 'Windows'] },
    { cat: 'infra', items: ['Docker', 'Proxmox', 'Caddy', 'Nginx', 'Tailscale'] },
    { cat: 'web',   items: ['TypeScript', 'Astro', 'React', 'Tailwind'] },
    { cat: 'data',  items: ['Postgres', 'Redis', 'SQLite'] },
    { cat: 'tools', items: ['Neovim', 'Tmux', 'Git', 'n8n'] },
    { cat: 'lang',  items: ['Python', 'Bash', 'Node.js', 'Rust'] },
  ],

  experience: [
    {
      year: '2026',
      role: { en: 'Freelance Web Dev', es: 'Desarrollador Web Freelance' },
      org: 'self',
      desc: {
        en: 'Shipping portfolio sites and tools with Astro + self-hosted infra. Fast, no-BS deployments on Cloudflare Pages.',
        es: 'Lanzando portfolios y herramientas con Astro + infra propia. Deploys rápidos en Cloudflare Pages.',
      },
      lvl: '+4',
      color: 'cyan',
      tags: ['Astro', 'TypeScript', 'Cloudflare', 'React'],
    },
    {
      year: '2025',
      role: { en: 'ASIR 2nd Year', es: 'ASIR 2.º Año' },
      org: 'IES Gijón',
      desc: {
        en: '2nd year of Network & Systems Admin. Deep-diving into routing, scripting, active directory, and Linux server hardening.',
        es: '2.º año de ASIR. Profundizando en routing, scripting, active directory y hardening de servidores Linux.',
      },
      lvl: '+3',
      color: 'magenta',
      tags: ['Linux', 'Networking', 'Active Directory', 'Bash'],
    },
    {
      year: '2024',
      role: { en: 'Homelab Pioneer', es: 'Pioneer del Homelab' },
      org: 'bedroom.local',
      desc: {
        en: 'First Proxmox node on an old rig. Broke it 10 times. Rebuilt 10 times. Self-hosted mail, DNS, VPN, monitoring.',
        es: 'Primer nodo Proxmox en un PC viejo. Lo rompí 10 veces. Lo reconstruí 10 veces. Correo, DNS, VPN, monitoring propios.',
      },
      lvl: '+2',
      color: 'gold',
      tags: ['Proxmox', 'Docker', 'Self-hosting', 'DNS'],
    },
    {
      year: '2025',
      role: { en: 'Linux Discovery', es: 'Descubrimiento de Linux' },
      org: 'github.com',
      desc: {
        en: 'Started with Linux last year. Went from "how do I install this?" to writing automation scripts in under 6 months.',
        es: 'Empecé con Linux el año pasado. De "¿cómo instalo esto?" a escribir scripts de automatización en menos de 6 meses.',
      },
      lvl: '+1',
      color: 'violet',
      tags: ['Linux', 'Bash', 'Python', 'Git'],
    },
  ],

  certs: [
    {
      id: 'claude-code-action',
      title: { en: 'Claude Code in Action', es: 'Claude Code en Acción' },
      issuer: 'Anthropic',
      glyph: 'AN',
      date: '2026-03',
      credId: 'wyt2tq7q79ab',
      skills: ['Claude Code', 'Agent SDK'],
      color: 'magenta',
    },
    {
      id: 'claude-bedrock',
      title: { en: 'Claude in Amazon Bedrock', es: 'Claude en Amazon Bedrock' },
      issuer: 'Anthropic',
      glyph: 'AN',
      date: '2026-04',
      credId: 'cwpo6gji4e3u',
      skills: ['Amazon Bedrock', 'Claude API'],
      color: 'cyan',
    },
    {
      id: 'agent-skills',
      title: { en: 'Introduction to Agent Skills', es: 'Introducción a Habilidades de Agentes' },
      issuer: 'Anthropic',
      glyph: 'AN',
      date: '2026-04',
      credId: 'jz3pzuffs6bh',
      skills: ['AI Agents'],
      color: 'violet',
    },
    {
      id: 'subagents',
      title: { en: 'Introduction to Subagents', es: 'Introducción a Subagentes' },
      issuer: 'Anthropic',
      glyph: 'AN',
      date: '2026-04',
      credId: 'psovy8i4b5tr',
      skills: ['Agents', 'AI'],
      color: 'gold',
    },
    {
      id: 'mcp-advanced',
      title: { en: 'Model Context Protocol: Advanced Topics', es: 'Model Context Protocol: Temas Avanzados' },
      issuer: 'Anthropic',
      glyph: 'AN',
      date: '2026-04',
      credId: 'w9hen7nosjw5',
      skills: ['MCP', 'Multi-agent'],
      color: 'magenta',
    },
    {
      id: 'nginx-cloudflare',
      title: { en: 'Nginx & Cloudflare End-to-End Encryption', es: 'Encriptación Nginx con Cloudflare' },
      issuer: 'OpenWebinars',
      glyph: 'OW',
      date: '2025-12',
      credId: null,
      skills: ['Nginx', 'Cloudflare', 'Security'],
      color: 'cyan',
    },
    {
      id: 'mcp-intro',
      title: { en: 'Learning MCP (Model Context Protocol)', es: 'Aprendiendo MCP (Model Context Protocol)' },
      issuer: 'OpenWebinars',
      glyph: 'OW',
      date: '2025-12',
      credId: null,
      skills: ['MCP', 'AI'],
      color: 'violet',
    },
  ],

  bootSeq: [
    { t: 0,   type: 'info', text: 'VOD-BIOS v2.4.1 — © vodtinker.dev' },
    { t: 80,  type: 'ok',   text: 'CPU ............ 8x ARCH-RISC @ 3.2GHz [OK]' },
    { t: 140, type: 'ok',   text: 'MEM ............ 16384 MB [OK]' },
    { t: 180, type: 'ok',   text: 'GPU ............ NEON-RTX [OK]' },
    { t: 230, type: 'warn', text: 'COFFEE ......... LOW [WARN]' },
    { t: 280, type: 'ok',   text: 'NETWORK ........ link up @ 1 Gb/s' },
    { t: 330, type: 'info', text: 'mounting /home/vodtinker ...' },
    { t: 390, type: 'ok',   text: 'mount: /home/vodtinker [OK]' },
    { t: 440, type: 'info', text: 'loading sprites ............ [████████████] 100%' },
    { t: 500, type: 'info', text: 'loading fonts .............. [████████████] 100%' },
    { t: 560, type: 'ok',   text: 'all systems nominal.' },
    { t: 620, type: 'info', text: 'launching portfolio.exe ...' },
  ],

  i18n: {
    en: {
      nav_about: 'about', nav_projects: 'projects', nav_stack: 'stack',
      nav_xp: 'experience', nav_comms: 'contact',
      hero_pretitle: 'NEW GAME — PRESS START',
      hero_title: 'Between servers', hero_title_2: 'and code.',
      hero_sub: 'ASIR student bridging Linux infrastructure and modern web development. I build systems that work quietly so people can focus on what matters.',
      hero_cta_1: 'View Quests', hero_cta_2: 'Open Comms',
      hero_terminal_label: 'TERMINAL — vodtinker@homelab',
      world_title: 'World Map', world_sub: 'Choose your destination. Click a zone.',
      about_banner: 'CHARACTER · LV.21', about_title: 'About the player',
      about_p1: "21yo ASIR student from Gijón. Picked up Linux last year — started by breaking Arch, ended up running a homelab full of self-hosted services.",
      about_p2: "I write Ansible playbooks, wrangle Docker stacks, and occasionally stay up too late making a REST API or a pixel-art portfolio behave properly.",
      about_p3: "If the system needs a manual, it's not done yet.",
      about_stats: 'Stat block',
      stat_focus: 'focus', stat_curiosity: 'curiosity', stat_patience: 'patience', stat_caffeine: 'caffeine',
      projects_banner: 'QUESTS · ACTIVE', projects_title: 'Featured quests',
      projects_sub: "Things I've built. Click any quest to view.",
      stack_banner: 'INVENTORY', stack_title: 'Equipped gear',
      stack_sub: 'Tools I reach for daily.',
      homelab_banner: 'HOMELAB · INFRA MAP', homelab_title: 'Infrastructure topology',
      homelab_sub: 'Netbird WireGuard mesh — all nodes P2P connected.',
      homelab_hover: 'HOVER A NODE',
      xp_banner: 'TIMELINE · XP LOG', xp_title: 'Experience log',
      certs_banner: 'ACHIEVEMENTS', certs_title: 'Certifications',
      certs_sub: 'Verified credentials and completed courses.',
      certs_verify: 'VERIFY',
      comms_banner: 'COMMS CHANNEL', comms_title: 'Send a transmission',
      comms_sub: 'Open a channel. I usually answer within 24h.',
      footer_built: 'Hand-rolled with Astro, React, and too much coffee.',
      footer_year: '© 2026',
      easter_hint: '↑ ↑ ↓ ↓ ← → ← → B A',
      stack_labels: { os: 'OS', infra: 'INFRA', web: 'WEB', data: 'DATA', tools: 'TOOLS', lang: 'LANGUAGES' },
    },
    es: {
      nav_about: 'sobre', nav_projects: 'proyectos', nav_stack: 'stack',
      nav_xp: 'experiencia', nav_comms: 'contacto',
      hero_pretitle: 'NUEVA PARTIDA — PULSA START',
      hero_title: 'Entre servidores', hero_title_2: 'y código.',
      hero_sub: 'Estudiante ASIR que conecta infraestructura Linux con desarrollo web moderno. Construyo sistemas que funcionan en silencio.',
      hero_cta_1: 'Ver Quests', hero_cta_2: 'Abrir Comms',
      hero_terminal_label: 'TERMINAL — vodtinker@homelab',
      world_title: 'Mapamundi', world_sub: 'Elige tu destino. Haz clic en una zona.',
      about_banner: 'PERSONAJE · LV.21', about_title: 'Sobre el jugador',
      about_p1: '21 años, estudiante ASIR en Gijón. Empecé con Linux el año pasado — primero rompiendo Arch, ahora con un homelab lleno de servicios autoalojados.',
      about_p2: 'Escribo playbooks de Ansible, gestiono stacks de Docker y de vez en cuando me quedo hasta tarde hasta que una API REST o una web pixel-art se comporta como debe.',
      about_p3: 'Si el sistema necesita un manual, es que todavía no está terminado.',
      about_stats: 'Stats',
      stat_focus: 'foco', stat_curiosity: 'curiosidad', stat_patience: 'paciencia', stat_caffeine: 'cafeína',
      projects_banner: 'QUESTS · ACTIVAS', projects_title: 'Quests destacadas',
      projects_sub: 'Cosas que he construido. Haz clic para ver.',
      stack_banner: 'INVENTARIO', stack_title: 'Equipo equipado',
      stack_sub: 'Herramientas del día a día.',
      homelab_banner: 'HOMELAB · MAPA INFRA', homelab_title: 'Topología de infraestructura',
      homelab_sub: 'Red mesh Netbird WireGuard — todos los nodos conectados P2P.',
      homelab_hover: 'HOVER UN NODO',
      xp_banner: 'CRONOLOGÍA · XP LOG', xp_title: 'Registro de experiencia',
      certs_banner: 'LOGROS', certs_title: 'Certificaciones',
      certs_sub: 'Credenciales verificadas y cursos completados.',
      certs_verify: 'VERIFICAR',
      comms_banner: 'CANAL DE COMMS', comms_title: 'Envía una transmisión',
      comms_sub: 'Abre un canal. Suelo responder en 24h.',
      footer_built: 'Hecho a mano con Astro, React y demasiado café.',
      footer_year: '© 2026',
      easter_hint: '↑ ↑ ↓ ↓ ← → ← → B A',
      stack_labels: { os: 'OS', infra: 'INFRA', web: 'WEB', data: 'DATOS', tools: 'HERRAMIENTAS', lang: 'LENGUAJES' },
    },
  },
} as const;

export type Lang = 'en' | 'es';
export type I18n = typeof PIXEL_DATA.i18n.en;
